# Generated by Django 5.1.4 on 2024-12-20 02:20

import weblogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogapp', '0002_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(blank=weblogapp.models.Tag, null=weblogapp.models.Tag),
            preserve_default=weblogapp.models.Tag,
        ),
    ]
