# Generated by Django 5.1.4 on 2024-12-20 03:16

import weblogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogapp', '0003_post_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(blank=weblogapp.models.Tag, default=0, null=weblogapp.models.Tag),
        ),
    ]
